language: java

jdk:
  - openjdk8

notifications:
  email: 
    recipients:
      - gary@sourceauditor.com
      - ybronshteyn@blackducksoftware.com
    on_success: change
    on_failure: always
after_success:
- mvn com.blackducksoftware.integration:hub-maven-plugin:1.4.0:createHubOutput -Dhub.output.directory=.
- bash <(curl -s https://copilot.blackducksoftware.com/bash/travis) ./*_bdio.jsonld

