package org.spdx.licenselist;

import java.util.HashMap;
import java.util.Map;
/*
 * This class is autogenerated by the LicenseListPublisher - DO NOT EDIT
 */


/**
 * 
 * SPDX Listed Licenses for version {{{version}}}
 *
 */
public enum SpdxListedLicenses implements ISpdxListedLicense {
	
	{{#licenseEnums}}{{{.}}}{{/licenseEnums}}
	
	static final Map<String, ISpdxListedLicense> iDLicenseMap = new HashMap<>();
	static {
		{{#licensePuts}}{{{.}}}{{/licensePuts}}
	}
	
	static ISpdxListedLicense getLicenseById(String licenseId) {
		return iDLicenseMap.get(licenseId);
	}

	private String licenseId;
	private String name;
	private String licenseText;
	private String standardLicenseTemplate;
	private String standardLicenseHeader;
	private String standardLicenseHeaderTemplate;
	private Boolean fsfLibre;
	private String[] seeAlso;
	private boolean osiApproved;
	private boolean deprecated;
	private String deprecatedVersion;
	private String comment;

	private SpdxListedLicenses(String licenseId, String name, String licenseText, String standardLicenseTemplate, 
			String standardLicenseHeader, String standardLicenseHeaderTemplate, String[] seeAlso,  Boolean fsfLibre,
			boolean osiApproved, boolean deprecated, String deprecatedVersion, String comment) {
		this.licenseId = licenseId;
		this.name = name;
		this.licenseText = licenseText;
		this.standardLicenseTemplate = standardLicenseTemplate;
		this.standardLicenseHeader = standardLicenseHeader;
		this.standardLicenseHeaderTemplate = standardLicenseHeaderTemplate;
		this.fsfLibre = fsfLibre;
		this.seeAlso = seeAlso;
		this.osiApproved = osiApproved;		
		this.deprecated = deprecated;
		this.deprecatedVersion = deprecatedVersion;
		this.comment = comment;
	}

	/**
	 * @return the licenseId
	 */
	public String getLicenseId() {
		return licenseId;
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @return the licenseText
	 */
	public String getLicenseText() {
		return licenseText;
	}

	/**
	 * @return the standardLicenseTemplate
	 */
	public String getStandardLicenseTemplate() {
		return standardLicenseTemplate;
	}

	/**
	 * @return the standardLicenseHeader
	 */
	public String getStandardLicenseHeader() {
		return standardLicenseHeader;
	}

	/**
	 * @return the standardLicenseHeaderTemplate
	 */
	public String getStandardLicenseHeaderTemplate() {
		return standardLicenseHeaderTemplate;
	}


	/**
	 * @return the seeAlso
	 */
	public String[] getSeeAlso() {
		return seeAlso;
	}

	/**
	 * @return the osiApproved
	 */
	public boolean isOsiApproved() {
		return osiApproved;
	}

	/**
	 * @return the deprecated
	 */
	public boolean isDeprecated() {
		return deprecated;
	}

	/**
	 * @return the deprecatedVersion
	 */
	public String getDeprecatedVersion() {
		return deprecatedVersion;
	}

	/**
	 * @return the comment
	 */
	public String getComment() {
		return comment;
	}

	/**
	 * @return the fsfLibre
	 */
	public Boolean getFsfLibre() {
		return fsfLibre;
	}

	public boolean isFsfLibre() {
		return fsfLibre != null && fsfLibre;
	}

	public boolean isNotFsfLibre() {
		return fsfLibre != null && !fsfLibre;
	}
	
	@Override
	public String toString() {
		return this.getLicenseId();
	}
}
